version: '3.9'
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=bagley
      - MARIADB_USER=bagley
      - MARIADB_PASSWORD=db_password
    volumes:
      - ./sql/bagley.sql:/docker-entrypoint-initdb.d/bagley.sql
    ports:
      - 3306:3306

  bagley:
    build: .
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=bagley
      - DB_USER=bagley
      - DB_PASSWORD=db_password
      - DISCORD_TOKEN=write_your_discord_token_here
    cap_add:
      - NET_ADMIN
    depends_on:
      - mariadb
    network_mode: "host"
    shm_size: '1gb'

