version: '3.9'
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=xwpogivnoqipwm,elvwp4ebqw`rv,
      - MARIADB_DATABASE=bagley
      - MARIADB_USER=bagley
      - MARIADB_PASSWORD=vgytufqiyoguwpifbnweie
    volumes:
      - ./sql/bagley.sql:/docker-entrypoint-initdb.d/bagley.sql
    network_mode: "host"
    expose: 
      - 3306

  bagley:
    build: .
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=bagley
      - DB_USER=bagley
      - DB_PASSWORD=vgytufqiyoguwpifbnweie
      - DISCORD_TOKEN=OTA3NzY1MTg1NTA5NDYyMDk2.YYr8NQ.gTmNzNO_RwEEFPgTrUkKcW5HuNk
    cap_add:
      - NET_ADMIN
    depends_on:
      - mariadb
    network_mode: "host"