PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE domains (name TEXT PRIMARY KEY NOT NULL);
CREATE TABLE paths (name TEXT PRIMARY KEY NOT NULL, parent TEXT DEFAULT NULL, domain TEXT NOT NULL, FOREIGN KEY (domain) REFERENCES domains(name), FOREIGN KEY (parent) REFERENCES paths(name));
COMMIT;
